# Assignment 7

## Part 1

In [1]:
# Import relevant libraries
import os
import sys
print('Python: {}'.format(sys.version))

import scipy
print('scipy: {}'.format(scipy.__version__))

import numpy as np
print('numpy: {}'.format(np.__version__))

import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
#pd.set_option("display.max_rows", None, "display.max_columns", None)
print('pandas: {}'.format(pd.__version__))

import sklearn
print('sklearn: {}'.format(sklearn.__version__))

from sklearn.metrics import accuracy_score, confusion_matrix,ConfusionMatrixDisplay, recall_score

print("Hello World!")

Python: 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]
scipy: 1.7.1
numpy: 1.19.2
pandas: 1.1.3
sklearn: 0.24.2
Hello World!


### Part 1

In [48]:
def computeprob(k0,i,row,ev,gamma,ps):
    newprob =[]
    for j,val in enumerate(row):
        
        #for termial states, prob=0
        if( (i==0 and j==0) or (i==4 and j==4) ):
            newprob.append(0)
        else:
            up    = k0[i-1][j] if ((i-1) >= 0) else val
            down  = k0[i+1][j] if ((i+1) <= 4) else val
            right = k0[i][j+1] if ((j+1) <= 4) else val
            left  = k0[i][j-1] if ((j-1) >= 0) else val
            prob = ev + gamma*ps*(up+down+right+left)
            
            newprob.append(prob)
            
    return newprob
            

In [49]:
print('*************')
print('Part-1-Policy Iteration')
print('*************')

actions = ['u', 'd', 'r', 'l'] #up down right left
reward = -1
pr = 0.25 #
ps = 0.25 #state transition probability
gamma = 1 # discount factor

ev = sum([reward * pr for i in actions])

k0 = np.array([[0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19], [20,21,22,23,0]])

itrs = 0
while True:
    
    if(itrs in [0,1,10]):
        print('Policy for Iteration:',itrs)
        print('*************')
        print(k0)
        print('*************')
    
    k1 = np.array([computeprob(k0,i,row,ev,gamma,ps) for i, row in enumerate(k0)])
    converged = True
    for i,j in zip(k0.ravel(),k1.ravel()):
        if(i != j):
            converged = False
            
    if converged:
        print('Optimal Policy Converged in iterations:',itrs)
        print('*************')
        print(k0)
        print('*************')
        break
    else:
        k0 = k1
        itrs = itrs+1

*************
Part-1-Policy Iteration
*************
Policy for Iteration: 0
*************
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23  0]]
*************
Policy for Iteration: 1
*************
[[ 0.    1.25  2.25  3.25  4.  ]
 [ 4.25  5.    6.    7.    7.75]
 [ 9.25 10.   11.   12.   12.75]
 [14.25 15.   16.   17.   11.75]
 [18.   18.75 19.75 14.75  0.  ]]
*************
Policy for Iteration: 10
*************
[[ 0.         -1.64863873 -1.93782711 -1.89110088 -1.87017441]
 [-0.58767605 -0.95679474 -1.08333015 -1.27284241 -1.37806797]
 [ 0.83974934  0.63328362  0.15605164 -0.36806297 -0.85833454]
 [ 2.60308933  2.16038513  1.3485508   0.17612457 -0.59553623]
 [ 3.68497849  3.11612225  1.91924191  0.46542645  0.        ]]
*************
Optimal Policy Converged in iterations: 1206
*************
[[  0.         -23.         -34.33333333 -39.66666667 -41.66666667]
 [-23.         -30.66666667 -36.33333333 -39.         -39.66666667]
 [-34.33333333 -36.3333

### Part 2

In [53]:
def computevalue(k0,i,row,ev,gamma,ps):
    newprob =[]
    for j,val in enumerate(row):
        
        #for termial states, prob=0
        if( (i==0 and j==0) or (i==4 and j==4) ):
            newprob.append(0)
        else:
            up    = ev + gamma*(k0[i-1][j] if ((i-1) >= 0) else val)
            down  = ev + gamma*(k0[i+1][j] if ((i+1) <= 4) else val)
            right = ev + gamma*(k0[i][j+1] if ((j+1) <= 4) else val)
            left  = ev + gamma*(k0[i][j-1] if ((j-1) >= 0) else val)
            prob = max(up,down,right,left)
            
            newprob.append(prob)
            
    return newprob

In [54]:
print('*************')
print('Part-1-Value Iteration')
print('*************')

actions = ['u', 'd', 'r', 'l'] #up down right left
reward = -1
pr = 0.25 #
ps = 0.25 #state transition probability
gamma = 1 # discount factor

ev = sum([reward * pr for i in actions])

k0 = np.array([[0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19], [20,21,22,23,0]])

itrs = 0
while True:
    
    if(itrs in [0,1,10]):
        print('Policy for Iteration:',itrs)
        print('*************')
        print(k0)
        print('*************')
    
    k1 = np.array([computevalue(k0,i,row,ev,gamma,ps) for i, row in enumerate(k0)])
    converged = True
    for i,j in zip(k0.ravel(),k1.ravel()):
        if(i != j):
            converged = False
            
    if converged:
        print('Optimal Policy Converged in iterations:',itrs)
        print('*************')
        print(k0)
        print('*************')
        break
    else:
        k0 = k1
        itrs = itrs+1

*************
Part-1-Value Iteration
*************
Policy for Iteration: 0
*************
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23  0]]
*************
Policy for Iteration: 1
*************
[[ 0.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 18.]
 [20. 21. 22. 22.  0.]]
*************
Policy for Iteration: 10
*************
[[ 0. 13. 13. 13. 13.]
 [13. 13. 13. 13. 13.]
 [13. 13. 13. 13. 13.]
 [13. 13. 13. 13. 13.]
 [13. 13. 13. 13.  0.]]
*************
Optimal Policy Converged in iterations: 27
*************
[[ 0. -1. -2. -3. -4.]
 [-1. -2. -3. -4. -3.]
 [-2. -3. -4. -3. -2.]
 [-3. -4. -3. -2. -1.]
 [-4. -3. -2. -1.  0.]]
*************
